version: '3'

services:
  db:
    image: mysql/mysql-server
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}

  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - USER
      - DB_BACKEND=mysql
      - DB_USER
      - DB_PASSWORD
      - DB_NAME
      - DB_HOST=db
      - DB_PORT=3306
      - DJANGO_BACKEND=amazon
      - AWS_ACCESS_ID
      - AWS_SECRET_KEY
      - AWS_S3_BUCKET

volumes:
  dbdata:
