# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-05 21:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geek_text', '0003_auto_20180404_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
    ]
