# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-19 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geek_text', '0009_auto_20180419_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='', max_length=16),
        ),
    ]
