# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-20 21:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geek_text', '0013_auto_20180420_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='geek_text.Profile'),
        ),
    ]
