# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-21 00:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geek_text', '0015_auto_20180420_1803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='zip_code',
            new_name='zipcode',
        ),
    ]
