# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-21 01:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geek_text', '0016_auto_20180420_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
