# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-21 01:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geek_text', '0017_auto_20180420_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('state', localflavor.us.models.USStateField(max_length=2)),
                ('city', models.CharField(max_length=12, null=True)),
                ('zipcode', localflavor.us.models.USZipCodeField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
