# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-24 05:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_details', '0003_auto_20180323_1054'),
        ('book_details', '0003_auto_20180315_2208'),
    ]

    operations = [
    ]
