# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-20 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_auto_20180406_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='saveForLater',
            field=models.BooleanField(default=False),
        ),
    ]
