# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-21 01:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_details', '0007_merge_20180406_2047'),
        ('carts', '0003_cartitem_saveforlater'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_details.Book')),
            ],
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='saveForLater',
        ),
    ]
